name: CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Verify Chrome versions
        run: |
          google-chrome --version
          chromedriver --version

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Cucumber Tests
        run: mvn test -Dbrowser=chrome -Dheadless=true

        # 5. Generate Allure report
      - name: Generate Allure Report
        run: mvn allure:report

          # 6. Upload report as artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin